# Generated by Django 4.2.7 on 2025-08-06 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('family_size', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('transport', 'Transportation'), ('diet', 'Diet'), ('waste', 'Waste Management'), ('general', 'General')], max_length=20)),
                ('impact_kg_co2', models.DecimalField(decimal_places=2, help_text='Potential CO2 savings in kg', max_digits=8)),
                ('indian_context', models.BooleanField(default=True, help_text='Tip specific to Indian context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Waste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('organic', 'Organic Waste'), ('plastic', 'Plastic Waste'), ('paper', 'Paper Waste'), ('glass', 'Glass Waste'), ('metal', 'Metal Waste'), ('electronic', 'Electronic Waste')], max_length=20)),
                ('quantity_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.household')),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('car_petrol', 'Car (Petrol)'), ('car_diesel', 'Car (Diesel)'), ('car_cng', 'Car (CNG)'), ('car_electric', 'Car (Electric)'), ('bike_petrol', 'Bike (Petrol)'), ('bike_electric', 'Bike (Electric)'), ('bus', 'Bus'), ('train', 'Train'), ('metro', 'Metro'), ('auto', 'Auto Rickshaw'), ('cycle', 'Cycle'), ('walk', 'Walking')], max_length=20)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('frequency_per_week', models.PositiveIntegerField(default=1)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.household')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('electricity', 'Electricity'), ('lpg', 'LPG'), ('kerosene', 'Kerosene'), ('biogas', 'Biogas'), ('firewood', 'Firewood'), ('charcoal', 'Charcoal')], max_length=20)),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=20)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.household')),
            ],
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(choices=[('rice', 'Rice'), ('wheat', 'Wheat'), ('pulses', 'Pulses'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('milk', 'Milk & Dairy'), ('eggs', 'Eggs'), ('chicken', 'Chicken'), ('mutton', 'Mutton'), ('fish', 'Fish'), ('processed_food', 'Processed Food')], max_length=20)),
                ('consumption_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.household')),
            ],
        ),
        migrations.CreateModel(
            name='CarbonFootprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_footprint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy_footprint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_footprint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diet_footprint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('waste_footprint', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='footprint.household')),
            ],
            options={
                'unique_together': {('household', 'month')},
            },
        ),
    ]
